- alias: Adjust Living Room Air Purifier in real-time
  trigger:
    - platform: time_pattern
      seconds: 30
  action:
    - service: xiaomi_miio.fan_set_buzzer_off
      entity_id: fan.living_room_air_purifier
    - service: fan.set_speed
      entity_id: fan.living_room_air_purifier
      data_template:
        speed: >
          {% if states.fan.living_room_air_purifier.attributes.aqi | int > 40 %}
            favorite
          {% elif states.fan.living_room_air_purifier.attributes.aqi | int > 7 %}
            auto
          {% else %}
            idle
          {% endif %}
          
- alias: Adjust Kitchen Air Purifier in real-time
  trigger:
    - platform: time_pattern
      seconds: 30
  action:
    - service: xiaomi_miio.fan_set_buzzer_off
      entity_id: fan.kitchen_air_purifier
    - service: fan.set_speed
      entity_id: fan.kitchen_air_purifier
      data_template:
        speed: >
          {% if states.fan.kitchen_air_purifier.attributes.aqi | int > 40 %}
            favorite
          {% elif states.fan.kitchen_air_purifier.attributes.aqi | int > 7 %}
            auto
          {% else %}
            idle
          {% endif %}

- alias: Adjust Bedroom Air Purifier in real-time
  trigger:
    - platform: time_pattern
      seconds: 30
  action:
    - service: xiaomi_miio.fan_set_volume
      entity_id: fan.bedroom_air_purifier
      data:
        volume: 0
    - service: fan.set_speed
      entity_id: fan.bedroom_air_purifier
      data_template:
        speed: >
          {% if states.fan.bedroom_air_purifier.attributes.aqi | int > 20 %}
            favorite
          {% elif states.fan.bedroom_air_purifier.attributes.aqi | int > 5 %}
            auto
          {% else %}
            idle
          {% endif %}

