
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

vacuum:
  platform: xiaomi_miio
  host: !secret vacuum_host
  token: !secret vacuum_token
  name: Vacuum Cleaner

fan:
  - platform: xiaomi_miio
    model: zhimi.airpurifier.v6
    host: !secret purifier_1_host
    token: !secret purifier_1_token
    name: Bedroom Air Purifier

  - platform: xiaomi_miio
    model: zhimi.airpurifier.m1
    host: !secret purifier_2_host
    token: !secret purifier_2_token
    name: Living Room Air Purifier

  - platform: xiaomi_miio
    model: zhimi.airpurifier.m1
    host: !secret purifier_3_host
    token: !secret purifier_3_token
    name: Kitchen Air Purifier

cloud: